package com.example.itsystem.model;

public enum CompanySector {
    FOOD_MANUFACTURING_PROCESSING,
    FOOD_SERVICE_RESTAURANT,
    HOTEL_RESORT_FNB,
    INSTITUTIONAL_FOOD_SERVICE,
    FOOD_RETAIL_DISTRIBUTION,
    FOOD_TECH_QUALITY_SAFETY,
    GOVERNMENT_REGULATORY,
    FOOD_ENTREPRENEURSHIP_SME,
    OTHERS
}
